### PR TITLE
Updated docker image to .NET 6 #10

### LINKED ISSUE #10: Tool 'microsoft.cst.devskim.cli' failed to install
https://github.com/ben-manes/caffeine/actions/runs/3279477252

```
/usr/bin/docker build -t 8d5581:d182c176c6074ef38b83ea8b6dbb4126 -f "/home/runner/work/_actions/microsoft/DevSkim-Action/v1/Dockerfile" "/home/runner/work/_actions/microsoft/DevSkim-Action/v1"
[90](https://github.com/ben-manes/caffeine/actions/runs/3279477252/jobs/5399124373#step:2:90)
  Sending build context to Docker daemon  15.36kB
[91](https://github.com/ben-manes/caffeine/actions/runs/3279477252/jobs/5399124373#step:2:91)
  
[92](https://github.com/ben-manes/caffeine/actions/runs/3279477252/jobs/5399124373#step:2:92)
  Step 1/6 : FROM mcr.microsoft.com/dotnet/sdk:5.0
[93](https://github.com/ben-manes/caffeine/actions/runs/3279477252/jobs/5399124373#step:2:93)
   ---> 9fec788bd1f9
[94](https://github.com/ben-manes/caffeine/actions/runs/3279477252/jobs/5399124373#step:2:94)
  Step 2/6 : RUN mkdir /tools
[95](https://github.com/ben-manes/caffeine/actions/runs/3279477252/jobs/5399124373#step:2:95)
   ---> Using cache
[96](https://github.com/ben-manes/caffeine/actions/runs/3279477252/jobs/5399124373#step:2:96)
   ---> 7e55326a1bf8
[97](https://github.com/ben-manes/caffeine/actions/runs/3279477252/jobs/5399124373#step:2:97)
  Step 3/6 : RUN dotnet tool install --tool-path /tools Microsoft.CST.DevSkim.Cli
[98](https://github.com/ben-manes/caffeine/actions/runs/3279477252/jobs/5399124373#step:2:98)
   ---> Running in 6a075c1ef3ad
[99](https://github.com/ben-manes/caffeine/actions/runs/3279477252/jobs/5399124373#step:2:99)
  error NU1202: Package Microsoft.CST.DevSkim.CLI 0.6.30 is not compatible with net5.0 (.NETCoreApp,Version=v5.0) / any. Package Microsoft.CST.DevSkim.CLI 0.6.30 supports: net6.0 (.NETCoreApp,Version=v6.0) / any
[100](https://github.com/ben-manes/caffeine/actions/runs/3279477252/jobs/5399124373#step:2:100)
  The tool package could not be restored.
[101](https://github.com/ben-manes/caffeine/actions/runs/3279477252/jobs/5399124373#step:2:101)
  Tool 'microsoft.cst.devskim.cli' failed to install. This failure may have been caused by:
[102](https://github.com/ben-manes/caffeine/actions/runs/3279477252/jobs/5399124373#step:2:102)
  
[103](https://github.com/ben-manes/caffeine/actions/runs/3279477252/jobs/5399124373#step:2:103)
  * You are attempting to install a preview release and did not use the --version option to specify the version.
[104](https://github.com/ben-manes/caffeine/actions/runs/3279477252/jobs/5399124373#step:2:104)
  * A package by this name was found, but it was not a .NET tool.
[105](https://github.com/ben-manes/caffeine/actions/runs/3279477252/jobs/5399124373#step:2:105)
  * The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
[106](https://github.com/ben-manes/caffeine/actions/runs/3279477252/jobs/5399124373#step:2:106)
  * You mistyped the name of the tool.
[107](https://github.com/ben-manes/caffeine/actions/runs/3279477252/jobs/5399124373#step:2:107)
  
[108](https://github.com/ben-manes/caffeine/actions/runs/3279477252/jobs/5399124373#step:2:108)
  For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool
[109](https://github.com/ben-manes/caffeine/actions/runs/3279477252/jobs/5399124373#step:2:109)
  The command '/bin/sh -c dotnet tool install --tool-path /tools Microsoft.CST.DevSkim.Cli' returned a non-zero code: 1
[110](https://github.com/ben-manes/caffeine/actions/runs/3279477252/jobs/5399124373#step:2:110)
  
[111](https://github.com/ben-manes/caffeine/actions/runs/3279477252/jobs/5399124373#step:2:112)
Error: Docker build failed with exit code 1

### LINKED ISSUE #12: error NU1202: Package Microsoft.CST.DevSkim.CLI 0.6.30 is not compatible with net5.0
Using the latest version of DevSkim from [the marketplace](https://github.com/marketplace/actions/devskim). Appears there is some error at the container level with the version of .NET currently in use? This is blocking the running of the credential scanner, as it does not get past the container build step as seen below.

image

Would like to understand from the team:

1. If my understanding of the root cause is correct.
2. What the ETA could be for a possible fix.

Main error
`error NU1202: Package Microsoft.CST.DevSkim.CLI 0.6.30 is not compatible with net5.0 (.NETCoreApp,Version=v5.0) / any.`

Full logs
```ps
2022-10-19T13:38:56.1474333Z ##[group]Build container for action use: '/home/runner/work/_actions/microsoft/DevSkim-Action/v1/Dockerfile'.
2022-10-19T13:38:56.1546159Z ##[command]/usr/bin/docker build -t 8d5581:3e1307436a9040f584f24b9b70bf9ed8 -f "/home/runner/work/_actions/microsoft/DevSkim-Action/v1/Dockerfile" "/home/runner/work/_actions/microsoft/DevSkim-Action/v1"
2022-10-19T13:38:59.8229167Z Sending build context to Docker daemon  15.36kB
2022-10-19T13:38:59.8230417Z 
2022-10-19T13:38:59.8675939Z Step 1/6 : FROM mcr.microsoft.com/dotnet/sdk:5.0
2022-10-19T13:39:00.0103722Z 5.0: Pulling from dotnet/sdk
2022-10-19T13:39:00.0517866Z c1ad9731b2c7: Pulling fs layer
... ugreg REDACTED this line, redundant pulling, checksum and download messages
2022-10-19T13:39:11.4445762Z 5fdeb3a38fe8: Pull complete
2022-10-19T13:39:12.0050784Z d395fb0767b4: Pull complete
2022-10-19T13:39:12.0168144Z Digest: sha256:3ff465d940de3e2c727794d92fd7bb649c498d4abd91bc9213ea7831ebf01f1e
2022-10-19T13:39:12.0189908Z Status: Downloaded newer image for mcr.microsoft.com/dotnet/sdk:5.0
2022-10-19T13:39:12.0214633Z  ---> 9fec788bd1f9
2022-10-19T13:39:12.0216753Z Step 2/6 : RUN mkdir /tools
2022-10-19T13:39:12.0603980Z  ---> Running in 84fe85f5fa45
2022-10-19T13:39:13.0600997Z Removing intermediate container 84fe85f5fa45
2022-10-19T13:39:13.0601823Z  ---> 6ff498ad6abb
2022-10-19T13:39:13.0602441Z Step 3/6 : RUN dotnet tool install --tool-path /tools Microsoft.CST.DevSkim.Cli
2022-10-19T13:39:13.0913160Z  ---> Running in c98636eb89c9
2022-10-19T13:39:15.5122045Z error NU1202: Package Microsoft.CST.DevSkim.CLI 0.6.30 is not compatible with net5.0 (.NETCoreApp,Version=v5.0) / any. Package Microsoft.CST.DevSkim.CLI 0.6.30 supports: net6.0 (.NETCoreApp,Version=v6.0) / any
2022-10-19T13:39:15.5664737Z [91mThe tool package could not be restored.
2022-10-19T13:39:15.5665497Z Tool 'microsoft.cst.devskim.cli' failed to install. This failure may have been caused by:
2022-10-19T13:39:15.5667394Z 
2022-10-19T13:39:15.5668640Z * You are attempting to install a preview release and did not use the --version option to specify the version.
2022-10-19T13:39:15.5669254Z * A package by this name was found, but it was not a .NET tool.
2022-10-19T13:39:15.5670037Z * The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
2022-10-19T13:39:15.5670556Z * You mistyped the name of the tool.
2022-10-19T13:39:15.5670806Z 
2022-10-19T13:39:15.5671133Z For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool
2022-10-19T13:39:15.7004363Z The command '/bin/sh -c dotnet tool install --tool-path /tools Microsoft.CST.DevSkim.Cli' returned a non-zero code: 1
2022-10-19T13:39:15.7004743Z [0m
2022-10-19T13:39:15.7031316Z ##[warning]Docker build failed with exit code 1, back off 4.447 seconds before retry.
2022-10-19T13:39:20.1482621Z ##[command]/usr/bin/docker build -t 8d5581:3e1307436a9040f584f24b9b70bf9ed8 -f "/home/runner/work/_actions/microsoft/DevSkim-Action/v1/Dockerfile" "/home/runner/work/_actions/microsoft/DevSkim-Action/v1"
2022-10-19T13:39:20.1724357Z Sending build context to Docker daemon  15.36kB
2022-10-19T13:39:20.1725407Z 
2022-10-19T13:39:20.2150291Z Step 1/6 : FROM mcr.microsoft.com/dotnet/sdk:5.0
2022-10-19T13:39:20.2156462Z  ---> 9fec788bd1f9
2022-10-19T13:39:20.2157067Z Step 2/6 : RUN mkdir /tools
2022-10-19T13:39:20.2227429Z  ---> Using cache
2022-10-19T13:39:20.2231264Z  ---> 6ff498ad6abb
2022-10-19T13:39:20.2232251Z Step 3/6 : RUN dotnet tool install --tool-path /tools Microsoft.CST.DevSkim.Cli
2022-10-19T13:39:20.2500754Z  ---> Running in 97ff5607382d
2022-10-19T13:39:22.6238381Z error NU1202: Package Microsoft.CST.DevSkim.CLI 0.6.30 is not compatible with net5.0 (.NETCoreApp,Version=v5.0) / any. Package Microsoft.CST.DevSkim.CLI 0.6.30 supports: net6.0 (.NETCoreApp,Version=v6.0) / any
2022-10-19T13:39:22.6741674Z [91mThe tool package could not be restored.
2022-10-19T13:39:22.6742248Z Tool 'microsoft.cst.devskim.cli' failed to install. This failure may have been caused by:
2022-10-19T13:39:22.6742498Z 
2022-10-19T13:39:22.6742711Z * You are attempting to install a preview release and did not use the --version option to specify the version.
2022-10-19T13:39:22.6743255Z * A package by this name was found, but it was not a .NET tool.
2022-10-19T13:39:22.6743610Z * The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
2022-10-19T13:39:22.6743936Z * You mistyped the name of the tool.
2022-10-19T13:39:22.6744087Z 
2022-10-19T13:39:22.6744569Z For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool
2022-10-19T13:39:22.8116855Z The command '/bin/sh -c dotnet tool install --tool-path /tools Microsoft.CST.DevSkim.Cli' returned a non-zero code: 1
2022-10-19T13:39:22.8147421Z [0m
2022-10-19T13:39:22.8149351Z ##[warning]Docker build failed with exit code 1, back off 4.102 seconds before retry.
2022-10-19T13:39:26.9156793Z ##[command]/usr/bin/docker build -t 8d5581:3e1307436a9040f584f24b9b70bf9ed8 -f "/home/runner/work/_actions/microsoft/DevSkim-Action/v1/Dockerfile" "/home/runner/work/_actions/microsoft/DevSkim-Action/v1"
2022-10-19T13:39:26.9381933Z Sending build context to Docker daemon  15.36kB
2022-10-19T13:39:26.9384742Z 
2022-10-19T13:39:26.9816405Z Step 1/6 : FROM mcr.microsoft.com/dotnet/sdk:5.0
2022-10-19T13:39:26.9820016Z  ---> 9fec788bd1f9
2022-10-19T13:39:26.9820655Z Step 2/6 : RUN mkdir /tools
2022-10-19T13:39:26.9843774Z  ---> Using cache
2022-10-19T13:39:26.9844447Z  ---> 6ff498ad6abb
2022-10-19T13:39:26.9845645Z Step 3/6 : RUN dotnet tool install --tool-path /tools Microsoft.CST.DevSkim.Cli
2022-10-19T13:39:27.0330548Z  ---> Running in 4714cc515152
2022-10-19T13:39:29.3897211Z error NU1202: Package Microsoft.CST.DevSkim.CLI 0.6.30 is not compatible with net5.0 (.NETCoreApp,Version=v5.0) / any. Package Microsoft.CST.DevSkim.CLI 0.6.30 supports: net6.0 (.NETCoreApp,Version=v6.0) / any
2022-10-19T13:39:29.4428787Z [91mThe tool package could not be restored.
2022-10-19T13:39:29.4429236Z Tool 'microsoft.cst.devskim.cli' failed to install. This failure may have been caused by:
2022-10-19T13:39:29.4429494Z 
2022-10-19T13:39:29.4429948Z * You are attempting to install a preview release and did not use the --version option to specify the version.
2022-10-19T13:39:29.4430390Z * A package by this name was found, but it was not a .NET tool.
2022-10-19T13:39:29.4430792Z * The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
2022-10-19T13:39:29.4431149Z * You mistyped the name of the tool.
2022-10-19T13:39:29.4431312Z 
2022-10-19T13:39:29.4431568Z For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool
2022-10-19T13:39:29.5822355Z The command '/bin/sh -c dotnet tool install --tool-path /tools Microsoft.CST.DevSkim.Cli' returned a non-zero code: 1
2022-10-19T13:39:29.5858154Z [0m
2022-10-19T13:39:29.5859499Z ##[endgroup]
2022-10-19T13:39:29.5974320Z ##[error]Docker build failed with exit code 1
2022-10-19T13:39:29.6134258Z Uploading runner diagnostic logs
2022-10-19T13:39:29.6772247Z Completed runner diagnostic log upload
2022-10-19T13:39:29.6772498Z Cleaning up orphan processes
```

### PR DESCRIPTION
**Pull request by BernieWhite**
- Updated docker image to .NET 6.
- Added self-tests to action.

Fixes #10
Fixes #12

@gfs

### CODE REVIEW

**Comment by ugreg** [comment]
@BernieWhite will this also fix #12?

**Comment by BernieWhite** [comment]
@ugreg Yes.

**Comment by BernieWhite** [comment]
@gfs Need help to merge this one.

**Comment by ugreg** [comment]
Thanks for the quick action on this all. @BernieWhite or @gfs, when would be a good time to retest this in our code? Is the fix deployed right away once merged into main?

**Comment by gfs** [comment]
I need to readjust the tag to point to the new head. It should be 10-15 minutes as I’m resolving another issue with the new workflow now.

**Comment by gfs** [comment]
@ugreg still waiting on Bernie or I to figure out what is incorrect with the new workflow, but I've tagged the release that just bumped to .NET 6 as v1.0.4 as well as v1

**Comment by ben-manes** [comment]
Thanks for jumping on this! I ran the action and got further, but it produced a malformed `devskim-results.sarif` (perhaps empty), so the `codeql-action/upload-sarif` step failed.

https://github.com/ben-manes/caffeine/actions/runs/3279520184/jobs/5408265072

**Comment by gfs** [comment]
@ben-manes I see the same thing when running the action. I'm not sure what is wrong at this point. I have double checked that the latest actual executable is working and outputting valid sarif locally.

**Comment by ben-manes** [comment]
maybe try running an action locally ([nektos/act](https://github.com/nektos/act))?

**Comment by gfs** [comment]
> maybe try running an action locally ([nektos/act](https://github.com/nektos/act))?

Whoa. That's neat! It seems now that it's something to do with the encoding of the generated sarif.

**Comment by ugreg** [comment]
> Thanks for jumping on this! I ran the action and got further, but it produced a malformed `devskim-results.sarif` (perhaps empty), so the `codeql-action/upload-sarif` step failed.
> 
> https://github.com/ben-manes/caffeine/actions/runs/3279520184/jobs/5408265072

Facing the same @gfs and @BernieWhite here's screenshot for more context.

Is the `upload-sarif-action.js` open source file related to this repo? I see the [source here in another repo](https://github.com/github/codeql-action/blob/f0a12816612c7306b485a22cb164feb43c6df818/lib/upload-sarif-action.js#L71). Maybe it's some issue with the JSON being sent (is the DevSkim sending JSON to the code-ql action in anyway?) to this [validateSarifFileSchema](https://github.com/github/codeql-action/blob/f0a12816612c7306b485a22cb164feb43c6df818/lib/upload-lib.js#L189) function?

image

**Comment by gfs** [comment]
I think that this is caused by the BOM markers being added to DevSkim's sarif output. I thought I had fixed it but I'm not so sure now as the BOM still seem to be being added.

**Comment by gfs** [comment]
https://github.com/microsoft/DevSkim/pull/411

I have a fix here that I've confirmed does not output the byte markers with Sarif correctly. Hoping this will resolve it once merged.

**Comment by ugreg** [comment]
> [microsoft/DevSkim#411](https://github.com/microsoft/DevSkim/pull/411)
> 
> I have a fix here that I've confirmed does not output the byte markers with Sarif correctly. Hoping this will resolve it once merged.

Got, will continue conversation in that PR.

**Comment by gfs** [comment]
For anyone just following here - I believe this is now resolved on the v1 tag.

**Comment by ugreg** [comment]
Works for me now, thanks so much for the fix!

**Pull request merged**
