### PR TITLE
Add option to ignore rule IDs

### PR DESCRIPTION
**Pull request by maj113**
I don't know how to test the action locally/on my repo, so I'm not 100% sure this works correctly

### CODE REVIEW

**Comment by maj113** [comment]
@microsoft-github-policy-service agree

**Review by gfs — APPROVED** [review]
LGTM.

**Comment by maj113** [comment]
> @maj113 Thanks for the contribution.

so I tested this locally now and it seems to not work properly (it only parses the first ID)
DevSkim doesn't actually have a example on how to use --exclude-rule-ids
but I tested devskim on my machine and it only ignored rules if it wasn't in quotes, for some reason when running the action docker passes it in quotes `..."GITHUB_WORKSPACE" "**/.git/**,**/bin/**" "DS176209, DS148264"`

image  

image

It still seems to report the second one

**Comment by gfs** [comment]
Hmm interesting I tested it with a single rule and it was working but forgot to test the multiple case. 

Have you tried comma separated without the space separating?

**Comment by maj113** [comment]
>Have you tried comma separated without the space separating?

that works! 
Needs change in readme then

**Comment by gfs** [comment]
> > Have you tried comma separated without the space separating?
> 
> that works! Needs change in readme then

#20.

**Comment by gfs** [comment]
> Maybe it would be a good idea to document --ignore-rule-ids a bit on the main [devskim](https://github.com/Microsoft/DevSkim) repo

I've added a usage example to the wiki: https://github.com/microsoft/DevSkim/wiki/Analyze-Command#ignore-rules-by-id

**Pull request merged**
