### PR TITLE
Fix docker test

### PR DESCRIPTION
**Pull request by BernieWhite**
- Updates to fix test workflow for uploading reports and docker build.

@gfs sorry missed some bits in the initial PR #11

### CODE REVIEW

**Comment by gfs** [comment]
@BernieWhite I'm not sure what the correct syntax is for the command you're using to run - but might it be that the arguments are not making it to the entrypoint? https://github.com/microsoft/DevSkim-Action/blob/main/entrypoint.sh

**Comment by gfs** [comment]
I ran into the same issues in #13 trying to fix the same issue

**Comment by gfs** [comment]
Closing #13 in favor or yours, basically the same changes.

**Comment by gfs** [comment]
I just double checked 0.6.29 on its own and it does seem to be outputting valid sarif

```json
{"$schema":"https://schemastore.azurewebsites.net/schemas/json/sarif-2.1.0-rtm.5.json","version":"2.1.0","runs":[{"tool":{"driver":{"name":"devskim","fullName":"Microsoft DevSkim Command Line Interface","version":"0.6.29+ccc5aa72f0","rules":[{"id":"DS169125","name":"Do not use outdated SSL/TLS protocols","fullDescription":{"text":"An outdated SSL/TLS protocol version is specified."},"help":{"text":"An outdated SSL/TLS protocol version is specified.","markdown":"Visit [https://github.com/Microsoft/DevSkim/blob/main/guidance/DS169125.md](https://github.com/Microsoft/DevSkim/blob/main/guidance/DS169125.md) for guidance on this issue."},"defaultConfiguration":{"level":"error"},"helpUri":"https://github.com/Microsoft/DevSkim/blob/main/guidance/DS169125.md"},
```

**Comment by gfs** [comment]
https://github.com/microsoft/DevSkim/pull/409

I tested the action here against devskim and the sarif appears to be being created in the right place and with the right contents - uploading the sarif directly as a build artifact.  This release updated the Sarif SDK dependency, but its still being reported as outputting sarif v2.1 so I'm not sure why the sarif uploader doesn't like it.

**Comment by gfs** [comment]
Also tested locally and sarif generation seems to be working (can load with https://microsoft.github.io/sarif-web-component/)

**Comment by BernieWhite** [comment]
@gfs Agreed. It's a little confusing. Could it be encoding?

**Comment by BernieWhite** [comment]
@gfs Interesting it is encoding. Maybe a change with the switch between .NET 6? What do you want to do?

**Comment by BernieWhite** [comment]
Got it to work with:

```yaml
    # Can the action run successful against the repo
    - name: Self test action
      uses: ./

    - name: Check file exists
      run: |
        cat ${{ github.workspace }}/devskim-results.sarif

        pwsh -c "Get-Content '${{ github.workspace }}/devskim-results.sarif' | Set-Content '${{ github.workspace }}/devskim-results2.sarif' -Encoding UTF8"

    # Make sure results exist and can by uploaded
    - name: Upload results
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: ${{ github.workspace }}/devskim-results2.sarif

```

**Comment by gfs** [comment]
@BernieWhite nice catch. Let me go check if the SarifSDK has an argument to force utf8

**Comment by BernieWhite** [comment]
I'll clean up my test code.

**Comment by gfs** [comment]
I might have figured it out. The output is UTF-8 but its UTF-8 with the byte order mark, which appears at the 0th character. Requires a change to DevSkim itself to address.

**Comment by gfs** [comment]
https://github.com/microsoft/DevSkim/pull/410

**Comment by gfs** [comment]
New build is out, retrying run

**Comment by gfs** [comment]
Seems to be fixed with https://github.com/microsoft/DevSkim/pull/411

**Comment by gfs** [comment]
Thanks for your help @BernieWhite.  I think this is resolved now, but let me know if you find otherwise.

**Pull request merged**
